name: Build and Push Multi-arch Docker Images

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      service_selector:
        description: 'services to build (comma-separated, or "all")'
        required: true
        default: "all"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Set matrix based on input
        id: set-matrix
        shell: bash
        run: |
          set -euo pipefail

          selector="${{ github.event.inputs.service_selector }}"

          if [ "$selector" = "all" ]; then
            RAW="$(find . -maxdepth 2 -name "Dockerfile" -exec dirname {} \;)"
            SERVICES_JSON="$(printf '%s' "$RAW" | sed 's|^\./||' | jq -R -s -c 'split("\n") | map(select(. != ""))')"
          else
            SERVICES_JSON="$(printf '%s' "$selector" | jq -R -s -c 'split(",") | map(gsub("^[[:space:]]+|[[:space:]]+$"; "")) | map(select(. != ""))')"
          fi

          echo "matrix={\"service\":$SERVICES_JSON}" >> "$GITHUB_OUTPUT"
          echo "Matrix: $SERVICES_JSON"

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        shell: bash
        run: |
          set -euo pipefail

          service_dir="${{ matrix.service }}"
          service_dir="${service_dir#./}"
          image_name="$(echo "$service_dir" | sed 's|/|-|g' | tr '[:upper:]' '[:lower:]')"

          echo "Building: context='$service_dir'  dockerfile='$service_dir/Dockerfile'  image=ghcr.io/${{ github.repository_owner }}/$image_name:latest"

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f "$service_dir/Dockerfile" \
            -t "ghcr.io/${{ github.repository_owner }}/$image_name:latest" \
            --push "$service_dir"
