name: Build and Push Multi-arch Docker Images

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      services:
        description: 'comma-separated list of services to build (e.g. "caddy,i2pd-tools")'
        required: false
        default: "caddy,i2pd-tools"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ${{ fromJson('["' + replace(replace(github.event.inputs.services, ' ', ''), ',', '","') + '"]') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          echo "Building images for ${{ matrix.service }}"
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f ${{ matrix.service }}/Dockerfile \
            -t ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:latest \
            --push ${{ matrix.service }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
